services:
  - type: web
    name: my-portfolio-website
    env: node
    buildCommand: yarn install && yarn build
    startCommand: node server.js
    envVars:
      - key: EMAIL_USER
        value: your_email@example.com
      - key: EMAIL_PASS
        value: your_password
